### ISSUE TITLE
/login view

### ISSUE THREAD

**Issue by sockyone** [sockyone/INT2208-7-2019#4]
- View: /login, show 'register' link to create user, login button, show 'forgot password', input invalid alert

**Comment by phamquynh2108** [comment]
File login and register:
[login.txt](https://github.com/sockyone/INT2208-7-2019/files/2906449/login.txt)
[register.txt](https://github.com/sockyone/INT2208-7-2019/files/2906450/register.txt)

**Comment by sockyone** [comment]
> File login and register:
> [login.txt](https://github.com/sockyone/INT2208-7-2019/files/2906449/login.txt)
> [register.txt](https://github.com/sockyone/INT2208-7-2019/files/2906450/register.txt)

đây là phần login, không up code của register. Up lại đúng chỗ
