### ISSUE TITLE
/nav bar

### ISSUE THREAD

**Issue by sockyone** [sockyone/INT2208-7-2019#6]
1. Navbar:
- View: Nav bar show user avatar, web's logo, good color quality, logout button, messenger direct button, home direct button
- Logic: Click to redirect to specific page

**Comment by nguyenchum99** [comment]
Navbar-html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="style1.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body style="background-color:#eaeae1;">


<nav class="navbar navbar-inverse"">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">RESPONSE APP</a>
    </div>	
    <ul class="nav navbar-nav " style="float:right;">
      <li><a href="#"><span class="glyphicon glyphicon-home"></span> News feed</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-comment"></span> Messenger</a></li>
      <li><a href="#"><img src="photo.jpg" alt="avatar"> User</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
    </ul>
  </div>
</nav>
</body>
</html>

Navbar-CSS

.container-fluid {
	width: 65%;
	height: 30px;
}

.navbar-fixed-top .navbar-header > a,
.navbar-inverse .navbar-header > a {
	font-family: "Arial Black", Gadget, sans-serif;
	font-size: 20px;
}

.navbar-inverse .navbar-nav > li > a {
	 font-size: 12px;
 }
 
 img {
	
	border-radius: 50%;
	width: 25px;
}

.box {
	margin-left:265px;
	height: 150px;
	width: 60%;
	border: 1px solid  #d9d9d9;
	border-radius: 5px;
	border-color: #d9d9d9;
	background-color: #ffffff;
}

.box .form-control {
	height: 70px;
	width: 85%;
	margin-left: 65px;
	margin-top: 20px;
	resize: none;
}


.register {
	margin-left: 200px;
	margin-top: 50px;
															
}

.form {
	width: 39%;
}

**Comment by sockyone** [comment]
@nguyenchum99 
upfile lên chứ không copy code vào đây (làm như Quỳnh)
